name: build

on:
  push:
    branches: [ main, development ]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: |
        npm run build
        npm run build:css

    - name: Run the tests
      run: npm test
